// Generated by CoffeeScript 2.1.0
(function () {
  $(function () {

    $('.notice').click(function (event) {
      event.preventDefault();
      event.stopPropagation();
      return $.growl.notice({
        message: "Service Added"
      });
    });
    
  });
}).call(this);